version: '2'

volumes:
  redis:
  postgres:

services:
  pgdata:
    image: busybox
    volumes:
      - './pgdata:/var/lib/postgresql/data'

#  redisdata:
#    image: busybox
#    volumes:
#      - './redisdata:/data'

  postgres:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_DB: $DATABASE
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - '5432:5432'
    volumes_from:
      - pgdata
    env_file:
      - '.env'

#  redis:
#    image: 'redis:4.0.2-alpine'
##    command: redis-server --requirepass yourpassword
#    command: redis-server
#    ports:
#      - '6379:6379'
#    volumes_from:
#      - redisdata

  website:
    depends_on:
      - 'postgres'
#      - 'redis'
    build: .
    external_links:
    - postgres:postgres
#    - redis:redis
    ports:
      - '3000:3000'
    # volumes:
    #   - '.:/app'
    env_file:
      - '.env'

#  sidekiq:
#    depends_on:
#      - 'postgres'
#      - 'redis'
#    build: .
#    command: sidekiq -C config/sidekiq.yml.erb
#    volumes:
#      - '.:/app'
#    env_file:
#      - '.env'

#  cable:
#    depends_on:
#      - 'redis'
#    build: .
#    command: puma -p 28080 cable/config.ru
#    ports:
#      - '28080:28080'
#    volumes:
#      - '.:/app'
#    env_file:
#      - '.env'
